name: Build and Deploy
run-name: Build and Deploy on PUSH
on: push
jobs:
  ci-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Docker build
        run: docker build -t ci .
      - name: Pylint
        run: docker run --entrypoint /bin/bash ci -c 'pip install pylint && pylint -E *.py'
      - name: Deploy
        if: ${{ github.ref_name != 'main' }}  
        run: echo "deploying now"
        run: echo ${{ secrets.IP }}
