name: Build and Deploy
run-name: Build and Deploy on PUSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Docker build
        run: docker build -t ci .
      - name: Pylint
        run: docker run --entrypoint /bin/bash ci -c 'pip install pylint && pylint -E *.py'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Vultr
        if: ${{ github.ref_name != 'main' }}  
        run: |
              echo "deploying now"
              mkdir ~/.ssh || true
              echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
              chmod 0600 ~/.ssh/id_rsa
              ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.IP }}
