name: Build and Deploy
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Docker build
        run: docker build -t ci .
      - name: Pylint
        run: docker run --entrypoint /bin/bash ci -c 'pip install pylint && pylint -E *.py'
